
# 7.4: Changing basis by solving equations

In [1]:

%load_ext autoreload
%autoreload 2
from jupyterthemes import jtplot
jtplot.style()

from ch07.vectors import *
from ch07.functions import *
from ch05.vector_drawing import *
import numpy as np

## Testing 2D system

In [6]:
matrix = np.array((
    (1,-1),
    (1, 1)
))

result = np.array((4,2))

np.linalg.solve(matrix, result)

array([ 3., -1.])

### 3D System

In [3]:
matrix = np.array((
    (1,-1,0),
    (0,-1,-1),
    (1,0,2)
))

result = np.array((1,3,-7))
np.linalg.solve(matrix, result)

array([ 3.,  2., -5.])

Exercise 7.27: How can you write the vector (5, 5) as a linear combination of (10, 1) (3, 2)?

In [5]:

matrix = np.array((
    (10, 3),
    (1, 2)
))

result = np.array((5,5))

np.linalg.solve(matrix, result)

array([-0.29411765,  2.64705882])

Exercise 7.28: Write the vector (3, 0, 6, 9) as a linear combination of the vectors (0, 0, 1, 1), (0, -2, -1, -1), (1, -2, 0, 2),
and (0, 0, -2, 1).

In [7]:
matrix = np.array((
    (0,0,1,0),
    (0,-2,-2,0),
    (1,-1,0,-2),
    (1,-1,2,1)
))

result = np.array((3,0,6,9))

np.linalg.solve(matrix, result)

array([ 1., -3.,  3., -1.])